### ISSUE TITLE
Incompatible with Benny's Original Motor Works in SP

### ISSUE THREAD

**Issue by sruckstar** [sruckstar/gta5-all-mp-vehicles-in-sp#1]
[tr0es](https://www.gta5-mods.com/users/tr0es): This mod not compatible with Benny's Original Motor Works in SP 1.9.1** mod. whenever im leaving benny's shop character stuck in car and also car names stuck corner of screen. Keyboard doesnt work after this cant leave this game, cant open menu but however game also working. i hearing all of aroud sounds like cars, nature etc.

https://www.gta5-mods.com/scripts/single-player-benny-s-original-motor-works

**Comment by Michael21107** [comment]
@sruckstar just a reminder so you dont forget bout this xd

**Comment by sruckstar** [comment]
No fix is possible (need a fix from the author of Benny's Original Motor Works in SP)
