### ISSUE TITLE
Riot2 blocking traffic

### ISSUE THREAD

**Issue by Michael21107** [sruckstar/gta5-all-mp-vehicles-in-sp#12]
as you can see riot2 in front of Vinewood PD is blocking traffic and the sidewalk a bit as well as looks completely out of place (i think i moved it a bit but only forward or backward which wouldn't change the issue)
![image](https://github.com/sruckstar/gta5-all-mp-vehicles-in-sp/assets/121039033/b05c7dfc-a626-42bd-a45d-7fac2cf5f34a)

**Comment by sruckstar** [comment]
Fixed, will be in the release with the next patch
