### ISSUE TITLE
2.0.2 No traffic cars

### ISSUE THREAD

**Issue by lionnesquaer** [sruckstar/gta5-all-mp-vehicles-in-sp#20]
Greetings!

No traffic cars in 2.0.2
I enabled traffic_cars_blips in ini file, can confirm there is no blips for traffic cars. Game spawn only parked.
GTAV version 1.0.3095.0

logs attached
[asiloader.log](https://github.com/sruckstar/gta5-all-mp-vehicles-in-sp/files/14420859/asiloader.log)
[ScriptHookV.log](https://github.com/sruckstar/gta5-all-mp-vehicles-in-sp/files/14420862/ScriptHookV.log)
[ScriptHookVDotNet.log](https://github.com/sruckstar/gta5-all-mp-vehicles-in-sp/files/14420863/ScriptHookVDotNet.log)

**Comment by sruckstar** [comment]
Download pre-release 2.0.2, it has cars in traffic. This version is being tested now and will be released soon.

**Comment by lionnesquaer** [comment]
yes, im talking about pre-realease. redownload and installed again, still no traffic cars only parked.

**Comment by sruckstar** [comment]
Cars should appear every 10 seconds near the parking lots where DLC cars appear. Are you sure you just didn't miss them in traffic?

**Comment by sruckstar** [comment]
@lionnesquaer I fixed the mod and brought back the blips of cars in traffic. Try to download the pre-release version and check again.

Note that after some time the car tag will disappear. This is for optimization purposes, as cars are created quite often.

**Comment by lionnesquaer** [comment]
@sruckstar I tested fix, and yes they appears in traffic at least i notice the blips, but in my opinion possibility to meet DLC car in traffic extremely low, i drive around the city around 10 min, and they appears everythere but not in my view sight, if i don't have blips i even dont even now they are somethere.

**Comment by sruckstar** [comment]
@lionnesquaer Yes, this is done on purpose to make these cars unique from the regular fleet.

But I plan to add the ability to customize how often the cars appear soon.

Thank you for the test and feedback!
