### ISSUE TITLE
Car list for v1.68 update?

### ISSUE THREAD

**Issue by r3538987** [sruckstar/gta5-all-mp-vehicles-in-sp#23]
Hello,
Just wanted update mod, but my client remains on old v.1.67, means script fails on loading some new vehicles, and crashes. 
Would be possible to find an car name list (codes) which got added on v1.68? 
Just to add these into blocklist.

Minor thing, also blacklist is not optional as I thought. Later figured out that that file is required, even if not used.

**Comment by Michael21107** [comment]
what client remains on 1.67?

**Comment by r3538987** [comment]
One you restrict from updating? 
Also I think 1.68 update from Zolika mods, so definitely I'm staying on older version. 
I could close this issue, as there are forks, which allow automatically restrict missing cars from spawning.

**Comment by Michael21107** [comment]
not sure what you mean by client but if it is just GTAV.exe, everyone uses its version number which is 1.0.3179.0 currently

**Comment by r3538987** [comment]
Game updates update archives with new content, and I'm assuming so do this mod. It has up to date car list to spawn.
But if user is not received latest update, but use latest mod, it will result that modification attempts to spawn not existing cars.

**Comment by Michael21107** [comment]
if its no longer relevant, i suggest you close this issue

**Comment by r3538987** [comment]
There is solution, but its kind of weird to find solution for issue here, elsewhere.
