### ISSUE TITLE
Issues with car spawn and streets traffic

### ISSUE THREAD

**Issue by majesticbmbr** [sruckstar/gta5-all-mp-vehicles-in-sp#25]
Cars start to spawn in the middle of the road and don't move. As time goes by, more cars will spawn on top of these already spawned cars. After a while, all traffic on the streets disappears.

Versions:
GTA 5, v1.0.3095.0_v2 Epic Game Store
All-MP-Vehicles-in-SP, v.2.0.4
GTA V SCRIPT HOOK, v1.0.3095.0
ScriptHookVDotNet, v3.6.0

**Comment by majesticbmbr** [comment]
![2024-04-07 235859](https://github.com/sruckstar/gta5-all-mp-vehicles-in-sp/assets/166304072/22174367-16a4-43ce-b906-6558f4673bac)
![2024-04-08 001926](https://github.com/sruckstar/gta5-all-mp-vehicles-in-sp/assets/166304072/094f6b02-94a1-465c-858c-5d3e2e565420)

**Comment by majesticbmbr** [comment]
These bugs start to reproduce after tuning the car in LSC.

**Comment by ixxexi** [comment]
Same here.

**Comment by sruckstar** [comment]
Fixed in the last patch
