### ISSUE TITLE
Togglable police cars

### ISSUE THREAD

**Issue by Michael21107** [sruckstar/gta5-all-mp-vehicles-in-sp#33]
add an option to disable the spawning of police cars in both traffic and parked since people may have mods with their police agencies assigning (mainly LSPDFR) and therefore this mod may conflict/mismatch with their preferences **or** delete the police cars from this script since i think its not ideal to have the same thing in 2 scripts (this and [_MP Police Vehicles in SP_](https://www.gta5-mods.com/scripts/mp-police-vehicles-in-sp))

**Comment by sruckstar** [comment]
Not relevant at the moment, as the feature has been removed from the mod.

**Comment by Michael21107** [comment]
> Not relevant at the moment, as the feature has been removed from the mod.

permanently?
