### ISSUE TITLE
Realistic vehicles only option

### ISSUE THREAD

**Issue by Michael21107** [sruckstar/gta5-all-mp-vehicles-in-sp#7]
add an option for only having spawning MP vehicles that are realistic, like modern helicopters and sports cars, not jet packs and oppressors

**Comment by sruckstar** [comment]
No longer relevant because cars can be added to a blacklist. Maybe in the future I will publish a ready-made list of unrealistic cars.

**Comment by Michael21107** [comment]
that would be dope
