### ISSUE TITLE
I not sure that mod properly work with last version GTA 5 [v 1.0.3028/1.67]

### ISSUE THREAD

**Issue by lionnesquaer** [sruckstar/gta5-all-mp-vehicles-in-sp#9]
Greetings @sruckstar!

I cruising around the city many time and i dont see DLC cars in traffic (option set to "on" in the config), mod install in script folder. I have seen parked DLC cars (but extremely rare). Probably they spawn but extremely rare. Maybe you have increase spawn chance of serial models.

**Comment by sruckstar** [comment]
Try enabling traffic_cars_blips (set to 1) and drive around the city. If nothing appears, send the file ScriptHookDotNet.log

**Comment by lionnesquaer** [comment]
Yes, they appears. But very rare.  I mean, it is possible more fill traffic with DLC serial cars. Like US muscle cars somekind like Buffalo, Dominator, Gauntlet, Vigero. More serial SUV. They are typical cars on the LA streets. But cars like Deluxo and more sport classic and supercars rarely. 
Like i imagine every 5-10 seconds game spawn serial car.
Every 15-20 second spawn rare car.
something like that.

**Comment by Michael21107** [comment]
@sruckstar

**Comment by Michael21107** [comment]
@sruckstar just fyi: if it's invalid, u can close it as the second option - not planned
